version: 0.0
os: linux
files:
  - source: s3://code-build-data/javaProject/target/gs-spring-boot-0.1.0.jar
    destination: /home/ubuntu/application
hooks:
  ApplicationStop:
     - location: script_stop_server.sh
       timeout: 180
  Install:
     - location: script_install.sh
       timeout: 180
  ApplicationStart:
     - location: script_start_server.sh
       timeout: 180
  ValidateService:
     - location: script_validate_application.sh
       timeout: 180

